name: "GitHub PR Reviewer"
description: "Reviews pull requests using OpenAI"
author: "Rakesh Reddy"
inputs:
  OPENAI_API_KEY:
    description: "Your OpenAI API Key"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token to access repo and comment"
    required: true
  GITHUB_EVENT_PATH:
    description: "Path to the GitHub event JSON file"
    required: true
  EXCLUDE:
    description: "Comma-separated list of files to exclude from review"
    required: false
    default: ""
  PULL_NUMBER:
    description: "Pull request number to review"
    required: true
  REPOSITORY:
    description: "Repository in the format owner/repo"
    required: true
    default: "${{ github.repository }}"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run PR reviewer script
      run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PULL_NUMBER: ${{ inputs.PULL_NUMBER }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
